import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Roadmap from "../components/Roadmap/index";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Road Map Of Courses It Gate Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
♥️        محتوي أقوي دبلومة بالشرق الأوسط

      </h1>
      <h1 className={styles.title}>
Web Development Outlines🤍

      </h1>
      <Roadmap/>
    </div>
  );
}
